package Controller;

import DBcontext.Database;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;

@WebServlet("/createOrder")
public class CreateOrderServlet extends HttpServlet {

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        // Get user ID and order date from request
        int userId = Integer.parseInt(request.getParameter("userId"));
        String orderDateStr = request.getParameter("orderDate");

        // Convert the order date to MySQL-compatible format (yyyy-MM-dd HH:mm:ss)
        String formattedOrderDate = formatOrderDate(orderDateStr);

        // Prepare database connection
        Connection conn = null;
        PreparedStatement stmtOrder = null;
        PreparedStatement stmtOrderItem = null;

        try {
            conn = Database.getConnection();

            // SQL query to insert order data (into orders table)
            String insertOrderSQL = "INSERT INTO orders (user_id, order_date) VALUES (?, ?)";
            stmtOrder = conn.prepareStatement(insertOrderSQL, PreparedStatement.RETURN_GENERATED_KEYS);

            // Set the parameters for the order
            stmtOrder.setInt(1, userId);
            stmtOrder.setString(2, formattedOrderDate);

            // Execute and get the generated order_id for the new order
            stmtOrder.executeUpdate();
            ResultSet generatedKeys = stmtOrder.getGeneratedKeys();
            int orderId = 0;
            if (generatedKeys.next()) {
                orderId = generatedKeys.getInt(1); // Get the order_id generated by the database
            }

            // SQL query to insert order items (into orderitems table)
            String insertOrderItemSQL = "INSERT INTO orderitems (order_id, property_id, title, price) VALUES ( ?, ?, ?, ?)";
            stmtOrderItem = conn.prepareStatement(insertOrderItemSQL);

            // Process each property (product) in the order
            for (int i = 0; i < request.getParameterValues("propertyId").length; i++) {
                // Get property details for each product
                int propertyId = Integer.parseInt(request.getParameterValues("propertyId")[i]);
                String title = request.getParameterValues("title")[i];
                double price = Double.parseDouble(request.getParameterValues("price")[i]);

                String address = request.getParameterValues("address")[i];

                // Set the parameters for the order item
                stmtOrderItem.setInt(1, orderId); // Use the generated orderId
                stmtOrderItem.setInt(2, propertyId);
                stmtOrderItem.setString(3, title);
                stmtOrderItem.setDouble(4, price);


                // Execute the SQL statement to insert the order item
                stmtOrderItem.executeUpdate();
            }

            // Redirect to checkout page after successful order insertion
            response.sendRedirect("checkout.jsp");

        } catch (SQLException e) {
            e.printStackTrace();
            response.sendRedirect("error.jsp"); // Redirect to error page if something goes wrong
        } finally {
            // Ensure the connection and statements are closed
            try {
                if (stmtOrderItem != null) stmtOrderItem.close();
                if (stmtOrder != null) stmtOrder.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    private String formatOrderDate(String orderDateStr) {
        try {
            // Define the input date format (assuming it's like 'Thu Nov 28 22:44:37 GMT+07:00 2024')
            SimpleDateFormat inputFormat = new SimpleDateFormat("EEE MMM dd HH:mm:ss z yyyy");

            // Parse the input date string to a Date object
            Date date = inputFormat.parse(orderDateStr);

            // Define the output format for MySQL (yyyy-MM-dd HH:mm:ss)
            SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

            // Return the formatted date as a string
            return outputFormat.format(date);
        } catch (Exception e) {
            e.printStackTrace();
            return null; // In case of error, return null or handle as needed
        }
    }
}
